version: '3'
services:
  app:
    image: spring-boot-mongo-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://benyahiamohamd:hama1234@cluster0.9qilaf4.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: auth_test